
name: SSL_Status

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: SSH Remote Commands
      
      run: |
            ls
            cat domain.txt | while read -r data ; do
            port="443"
            echo $data
            dates=$(openssl s_client -connect "$data:$port" 2>/dev/null | openssl x509 -noout -dates)
            echo $dates
            done
            
