
name: SSL_Status

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: SSH Remote Commands
      
      run: |
            ls
            while read -r data ; do
            port="443"
            echo $data
            dates=$(openssl s_client -connect "$data:$port" 2>/dev/null | openssl x509 -noout -dates)
             # Extract "Not Before" and "Not After" dates
            not_before=$(echo "$dates" | grep "notBefore" | cut -d "=" -f 2)
            not_after=$(echo "$dates" | grep "notAfter" | cut -d "=" -f 2)
            
            # Convert dates to Unix timestamps for comparison
            not_before_unix=$(date -d "$not_before" +%s)
            not_after_unix=$(date -d "$not_after" +%s)
            current_unix=$(date +%s)
            
            # Check if the current date is within the validity range
            if [ "$current_unix" -ge "$not_before_unix" ] && [ "$current_unix" -le "$not_after_unix" ]; then
                echo "Certificate for $data is valid."
                curl -X POST -H 'Content-type: application/json' --data '{"text":"Certificate for $data is valid."}' ${{secrets.SLACK_URL}}

            else
                echo "Certificate for $domain is expired or not yet valid."
                curl -X POST -H 'Content-type: application/json' --data '{"text":"Certificate for $domain is expired or not yet valid."}' ${{secrets.SLACK_URL}}


            fi
            done < "doamin.txt"
            
